// These styles apply to every route in the application
import './globals.css'
import { IBM_Plex_Sans_Thai } from 'next/font/google'

// โหลดฟอนต์ IBM Plex Sans Thai
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ['thai'], // ระบุ subsets ถ้าต้องการรองรับภาษาไทย
  weight: ['100', '200', '300', '400', '500', '600', '700'], // ระบุช่วงน้ำหนักของฟอนต์
})

export const metadata = {
  title: 'University',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={ibmPlexSansThai.className} >
        <div className='min-h-screen w-screen'>{children}</div>
      </body>
    </html>
  )
}
