// These styles apply to every route in the application
import './globals.css'
import { IBM_Plex_Sans_Thai } from 'next/font/google'

// โหลดฟอนต์ IBM Plex Sans Thai
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ['thai'], // ระบุ subsets ถ้าต้องการรองรับภาษาไทย
  weight: ['100', '200', '300', '400', '500', '600', '700'], // ระบุช่วงน้ำหนักของฟอนต์
})

export const metadata = {
  title: 'University',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <html lang="th">
      <body className={`${ibmPlexSansThai.className} m-0 p-0`}>
        <div className="w-full max-w-screen min-h-screen overflow-y-auto box-border">
          {children}
        </div>
      </body>
    </html>
  )
}
